In [19]:
from utils import load_data, accuracy

In [20]:
adj, features, labels, idx_train, idx_val, idx_test = load_data(dataset='cora')

Loading cora dataset...
successfully loading data


In [27]:
import torch
c=0.5
node_number=adj.shape[0]
w=adj.clone()
w=w/w.sum(0)
E=torch.eye(node_number)
graph_feature=(1-c)*((E-c*w).inverse()).T

graph_feature.sum(axis=1)

tensor([1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000])

In [33]:
data1=torch.tensor([[1,1,1],[2,2,2]])
data2=torch.tensor([[3,3],[4,4]])
torch.concat([data1,data2],dim=1)

tensor([[1, 1, 1, 3, 3],
        [2, 2, 2, 4, 4]])

In [6]:
data/data.sum(axis=0)

array([[0.08333333, 0.13333333, 0.16666667],
       [0.33333333, 0.33333333, 0.33333333],
       [0.58333333, 0.53333333, 0.5       ]])