In [2]:
import numpy as np
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
data.sum(axis=1)

array([ 6, 15, 24])

In [6]:
data/data.sum(axis=0)

array([[0.08333333, 0.13333333, 0.16666667],
       [0.33333333, 0.33333333, 0.33333333],
       [0.58333333, 0.53333333, 0.5       ]])